variable "project" { type = string }
variable "env" { type = string }

variable "vpc_id" { type = string }
variable "private_subnet_ids" { type = list(string) }

variable "allowed_sg_ids" {
  description = "SG IDs permitted to reach the DB on 5432. Use SG-to-SG references, not CIDRs."
  type        = list(string)
  default     = []
}

variable "db_name" { type = string }
variable "db_username" { type = string }
# db_password is intentionally absent — generated by random_password, stored in Secrets Manager.

variable "engine_version" {
  type    = string
  default = "16.3"
}

variable "instance_class" {
  description = "db.t3.micro = free tier eligible (750 hrs/month, first 12 months)."
  type        = string
  default     = "db.t3.micro"
}

variable "allocated_storage" {
  description = "Free tier: up to 20 GB."
  type        = number
  default     = 20
}

variable "storage_type" {
  type    = string
  default = "gp3"
}

variable "multi_az" {
  description = "Multi-AZ deployment. NOT free tier — doubles compute and storage cost."
  type        = bool
  default     = false
}

variable "publicly_accessible" {
  type    = bool
  default = false
}

variable "deletion_protection" {
  description = "Flip to true for prod."
  type        = bool
  default     = false
}

variable "skip_final_snapshot" {
  description = "Set to false for prod — you want that last snapshot."
  type        = bool
  default     = true
}

variable "backup_retention_period" {
  description = "Days to retain automated backups. 0 = off."
  type        = number
  default     = 7
}

variable "secret_recovery_window_days" {
  description = "SM secret recovery window in days. 0 = force-delete (dev). Use 30 for prod."
  type        = number
  default     = 0
}

variable "tags" {
  type    = map(string)
  default = {}
}
